// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keulubieiikreswrrkiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtldWx1YmllaWlrcmVzd3Jya2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTMxNzMsImV4cCI6MjA3MjMyOTE3M30.1UAKRJdaw5daYW0voHJ2Yq25ugam68iA2W-YER-MF_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});